name: make pull request from issue

on:
  issues:
    types: [labeled]

jobs:
  sync:
    if: github.event.label.name == 'enhancement'
    name: Run test flow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: git setting 
        run : |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
      - name: file update
        run : echo "test!" >> test_files/test_file
      - name: commit
        run : |
          git stage test_files/test_file
          git commit -m "test commit!"
      - name: PullRequest
        uses: peter-evans/create-pull-request@v4
        with : 
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "issue#${{github.event.issue.number}}_enhancement"
          delete-branch: true
          title: "issue#${{github.event.issue.number}} ${{github.event.issue.title}}"